### ISSUE TITLE
Packages ipw2100-fw & ipw2200-fw no longer available

### ISSUE THREAD

**Issue by gascodes** [arch-linux-calamares-installer/alci-iso-pure#1]
Hi! Erik
Sorry for the nuisance, but packages "ipw2100-fw" and "ipw2200-fw" are no longer available.
I don't know if you could correct "packages.x86_64" list
Thanks for all the work you share

Hugs from Argentina
Gastón

**Comment by arcolinuxz** [comment]
let us see if it was a mistake

packages are here

https://github.com/arcolinux/arcolinux_repo_iso/tree/main/x86_64

cheers
erik

**Comment by arcolinuxz** [comment]
this is how/where you follow it up

https://gitlab.archlinux.org/archlinux/archiso/-/commit/8afa2b65d54b51518c14b7d587c6c624b7ed6352
